### ISSUE TITLE
Runtimes should insert bundle contents at `/cnab/bundle.json`

### ISSUE THREAD

**Issue by astrieanna** [deislabs/cnab-go#123]
In the [cnab-spec](https://github.com/deislabs/cnab-spec/blob/master/103-bundle-runtime.md#bundle-definition), it says:
>The bundle definition is made accessible from inside the invocation image in order to allow the run tool to reference information in the file. The bundle.json MUST be mounted to /cnab/bundle.json.

When I run `duffle install mybundle.json --bundle-is-file`, there is no file at `/cnab/bundle.json`.

cc @youreddy

**Comment by youreddy** [comment]
This should be apart of [Duffle's 1.0 Milestone](https://github.com/deislabs/duffle/milestone/2).
