### ISSUE TITLE
Release and semantic versioning for this repo

### ISSUE THREAD

**Issue by radu-matei** [deislabs/cnab-go#16]
We should stop relying on revisions for importing this repo and start using semantic versions.

@carolynvs suggested we start with a `v0.1.0`.

Thoughts?

**Comment by carolynvs** [comment]
I approve this versioning scheme. 😀

**Comment by jeremyrickard** [comment]
👍 for me.

When the CNAB spec is 1.0, we can work toward making cnab-go be `v1.0.0`

Will work on getting a cadence setup starting maybe next week?
