### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by radu-matei** [deislabs/cnab-go#3]
I think we can use the same Brigade instance from Duffle.
Once @vdice confirms, and creates a new project for us, I'll go ahead and add  basic config to test this package.

**Comment by vdice** [comment]
@radu-matei Ok, project created (https://brigadecore.github.io/kashti/projects/brigade-26fc63dd9a6f30ca177554b5ffe0137e3f753f9c20950810452279) and our default GH app, `deislabs-ci` is now installed on this repo.   We should be set to add a brigade.js file.
