### ISSUE TITLE
Migrate duffle driver implementations to cnab-go

### ISSUE THREAD

**Issue by jlegrone** [deislabs/cnab-go#49]
The driver interface is already defined in the [driver](https://github.com/deislabs/cnab-go/blob/8507768ec67ce0d427f7b71f784eda67ffbe94f6/driver/driver.go) package. Many of the [driver implementations from duffle](https://github.com/deislabs/duffle/tree/e50cd9ec76e31da9126b18aa7a0e0eedd379cc1c/pkg/driver) are generally useful outside of duffle and should be made available without the need for declaring a dependency on duffle.

**Comment by jlegrone** [comment]
While the APIs in cnab-go are fairly new, this would also help minimize the downstream impacts of refactors like https://github.com/deislabs/cnab-go/pull/28.

**Comment by silvin-lubecki** [comment]
I agree with moving the drivers here, as it's a main concept in CNAB implementations, and sharing common code between all CNAB runtime clients will reduce interoperability issues 👍
