### ISSUE TITLE
Delete mapstructure annotations

### ISSUE THREAD

**Issue by glyn** [deislabs/cnab-go#91]
Now that `duffle` no longer uses viper, we've stripped the mapstructure annotations out of duffle and we can do the same for cnab-go unless some other user of cnab-go depends on these annotations. There may be only one way to find out...

**Comment by vdice** [comment]
How would we feel about replacing `mapstructure` tags with `yaml` tags?  We've seen the need/use for the latter in https://github.com/deislabs/cnab-go/pull/90 and https://github.com/deislabs/cnab-go/pull/92.  Asking on this ticket as a quick search/replace will be easier than deleting the tags in one PR and adding new ones in a subsequent PR.

**Comment by vdice** [comment]
Addressed in https://github.com/deislabs/cnab-go/pull/95; closing.
